image: docker:19.03.8

variables:
  DEBUG: "FALSE"
  SECRET_KEY: "SECRET_KEY"
  DEBIAN_FRONTEND: noninteractive
  CI_REGISTRY: hub.sekhnet.ra/budget
  CI: "TRUE"


stages:
  - build-dev
  - qa
  - build-prod

build-dev:
  image: docker:19.03.8
  stage: build-dev
  script:
    - docker build -t "$CI_REGISTRY:$DEV_VERSION" .
    - docker push "$CI_REGISTRY:$DEV_VERSION"

test:
  stage: qa
  image: "$CI_REGISTRY:$DEV_VERSION"
  script:
    - /venv/bin/python manage.py test

format:
  stage: qa
  image: "$CI_REGISTRY:$DEV_VERSION"
  script:
    - /venv/bin/black --check /code

flake8:
  stage: qa
  image: "$CI_REGISTRY:$DEV_VERSION"
  script:
    - /venv/bin/flake8 --config .flake8 /code

build-prod:
  image: docker:19.03.8
  stage: build-prod
  only:
    - master
  script:
    - docker build -t "$CI_REGISTRY:latest" .
    - docker push "$CI_REGISTRY:latest"
