---
version: '3'
services:
 db:
  image: postgres
  environment:
   - POSTGRES_DB=budget
   - POSTGRES_USER=budget
   - POSTGRES_PASSWORD=budget
  volumes:
   - ./flutter/postgres-data:/var/lib/postgresql
 api:
  image:  'hub.sekhnet.ra/budget:v2.0'
  build: .
  environment:
   - DB=postgres
   - DB_HOST=db
   - DB_USER=budget
   - DB_PASS=budget
   - DEBUG=FALSE
   - SECRET_KEY='TRUE'
  ports:
   - "8000:8000"
  depends_on:
   - db
