---
version: '3'
services:
 db:
  image: postgres
  environment:
   - POSTGRES_DB=budget
   - POSTGRES_USER=budget
   - POSTGRES_PASSWORD=budget
  volumes:
   - ./flutter/postgres-data:/var/lib/postgresql
 api:
  image: hub.sekhnet.ra/budget
  build: .
  command: /venv/bin/python manage.py runserver 0.0.0.0:8000
  environment:
   - DB=postgres
   - DB_HOST=db
   - DB_USER=budget
   - DB_PASS=budget
   - DEBUG=TRUE
   - SECRET_KEY='TRUE'
  volumes:
   - .:/code
  ports:
   - "8000:8000"
  depends_on:
   - db
