apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backend.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend.fullname" . }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: {{ include "backend.fullname" . }}
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: {{ include "backend.fullname" . }}-secret
              key: DB_HOST
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "backend.fullname" . }}-secret
              key: SECRET_KEY
        - name:  DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "backend.fullname" . }}-secret
              key: DB_USER
        - name:  DB_PASS
          valueFrom:
            secretKeyRef:
              name: {{ include "backend.fullname" . }}-secret
              key: DB_PASS
        - name:  DB
          valueFrom:
            secretKeyRef:
              name: {{ include "backend.fullname" . }}-secret
              key: DB
        - name: DEBUG
          valueFrom:
            secretKeyRef:
              name: {{ include "backend.fullname" . }}-secret
              key: DEBUG
