apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}
data:
  DB_HOST: {{ .Values.db.DB_HOST }}
  DB_USER: {{ .Values.db.DB_USER }}
  DB_PASS: {{ .Values.db.DB_PASS }}
  DB: {{ .Values.db.DB }}
  SECRET_KEY: {{ .Values.django.SECRET_KEY }}
  DEBUG: {{ .Values.django.DEBUG }}
