apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
data:
  DB_HOST: {{ .Values.db.DB_HOST | b64enc | quote }}
  DB_USER: {{ .Values.db.DB_USER | b64enc | quote }}
  DB_PASS: {{ .Values.db.DB_PASS | b64enc | quote }}
  DB: {{ .Values.db.DB | b64enc | quote }}
  SECRET_KEY: {{ .Values.django.SECRET_KEY | b64enc | quote }}
